alias dm=docker-machine

read "NUTANIX_ENDPOINT?NUTANIX_ENDPOINT: "
export NUTANIX_ENDPOINT
read "NUTANIX_CLUSTER?NUTANIX_CLUSTER: "
export NUTANIX_CLUSTER
export NUTANIX_INSECURE=true
read "NUTANIX_VM_IMAGE?NUTANIX_VM_IMAGE: "
export NUTANIX_VM_IMAGE
export NUTANIX_VM_IMAGE_SIZE=20
read "NUTANIX_VM_NETWORK?NUTANIX_VM_NETWORK: "
export NUTANIX_VM_NETWORK
read "NUTANIX_USERNAME?NUTANIX_USERNAME: "
export NUTANIX_USERNAME
read "NUTANIX_PASSWORD?NUTANIX_PASSWORD: "
export NUTANIX_PASSWORD

