version: 2

project_name: docker-machine-driver-nutanix

builds:
  - goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}"
    formats: binary

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
