name: Black Duck Intelligent Policy Check
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  security:
    if: github.repository == 'nutanix/docker-machine'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.17"

      - name: Build Project
        run: make build

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@v0.3.4
        env:
          DETECT_PROJECT_USER_GROUPS: CloudNative
        with:
          scan-mode: INTELLIGENT
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.10.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
